apiVersion: v1
kind: Pod
metadata:
  name: security-context-ubuntu
spec:
  securityContext:
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: sec-ctx-ubuntu
    image: ubuntu:latest
    command:
    - "/bin/bash"
    args:
    - "-c"
    - "sleep 3600"
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 2000